// Code generated by "stringer -type Type"; DO NOT EDIT.

package metricdata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeGaugeInt64-0]
	_ = x[TypeGaugeFloat64-1]
	_ = x[TypeGaugeDistribution-2]
	_ = x[TypeCumulativeInt64-3]
	_ = x[TypeCumulativeFloat64-4]
	_ = x[TypeCumulativeDistribution-5]
	_ = x[TypeSummary-6]
}

const _Type_name = "TypeGaugeInt64TypeGaugeFloat64TypeGaugeDistributionTypeCumulativeInt64TypeCumulativeFloat64TypeCumulativeDistributionTypeSummary"

var _Type_index = [...]uint8{0, 14, 30, 51, 70, 91, 117, 128}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
